### Variables

@baseurl = http://localhost:3333
# Health check
GET {{baseurl}}/health

###

# Create room
# @name createRoom

POST {{baseurl}}/rooms
Content-Type: application/json

{
  "name": "Room 1",
  "description": "Description 1"
}
###

# Get rooms
# @name getRooms
GET {{baseurl}}/rooms

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
GET {{baseurl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseurl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "Question 2"
}
###
